import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex min-h-screen">
          {/* Sidebar - Fixed width */}
          <div className="w-10  text-white z-10">
            <Sidebar />
          </div>

          {/* Main Content - Expands */}
          <main className="flex-1 p-6 bg-gray-50 overflow-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
